
### First Request

# this is a comment

GET http://example.com
Authorization: Bearer token

> {%
  console.log("hello");
  1 + 1;
%}

### Second Request

PATCH /localhost/path
Authorization: Bearer token
Content-Type: application/json

{
  "id": 1,
  "foo": "bar"
}

> post.script

> {% 


%}

> {% %}

###

### asd

POST http://example.com?
    # /another-path:foo&
    # /baz
    # /path
Authorization: Bearer
# foo: 1
Accept: */*
# bar: 2
# baz: 3

# foo

body
# foo

### Third Request

POST http://localhost/path
Authorization: Bearer token
Content-Type: application/xml

<xml>
    <foo>1</foo>
</xml>

###
